language: scala
scala:
- 2.11.8
jdk:
- oraclejdk7
script:
- cd 2-repositories/scala-repo-server
- ./scripts/create-test-user.bash
- sbt test
- cd ../..
deploy:
- provider: script
  skip_cleanup: true
  script: ./.travis/deploy.py
  on:
    condition: '"$(.travis/is_core_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0 && "${TRAVIS_SCALA_VERSION}" == "2.11.8"'
    tags: true
- provider: script
  skip_cleanup: true
  script: ./.travis/deploy.py
  on:
    condition: '"$(.travis/is_schemaddl_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0 && "${TRAVIS_SCALA_VERSION}" == "2.11.8"'
    tags: true
- provider: script
  skip_cleanup: true
  script: ./.travis/deploy.py
  on:
    condition: '"$(.travis/is_igluctl_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0 && "${TRAVIS_SCALA_VERSION}" == "2.11.8"'
    tags: true
env:
  global:
  - secure: giEJ6EdAXy+clvVBfkV42t6SH7Ze1DSdTrpAucLXHOl4UF7J+TgECDIPeSbhy/y3g4cDFb37mB1dl1gOv5UYuBm8/92Agj+oQpK49nRsc4+xXeEpraHEGlq1L+BW0zVZx+w6M3eTBu9uT0skDAF3aeVFu7BJtTonrQh2Fr+RD3I=
  - secure: LQIIIape04LUL4cv2SMS10AVlHofxPO0HxcT12EAefSuHJyGfMYKSAIywloPQob/rCeGcWIICCycgXfx3O4joM+axI4tZuNoGQ7LyiJrIEFDtGdFW5Cl+fZwJXtaYEy+fDBCwi+c+oK6olSDyXgNXj4EVZgOYuDxJ8FexQDj6Ok=
  - secure: "D5Egj4tqCXpL7H4x/BsPs9tOVX7Q20ooaB5e7+KDBk9PdLFFLHGMJP6+lRjmLNnX89ngWSNmPyu9L5qJ8D4Bmuy+s2bMN8iM/bryJrGvAMUjLXnVEaENn4hd7Xn6zA0JoTvyk8jEiLlTsZakpz8j8N6g9mscZXsMoXtRWFOnE0s="
  - secure: "NuQTaOT/cgld8PE6QWAKiEFQcxmOJ46Gfq7hyNVte2fRICfkOz531mnPNcX5Zak+Z1S1gW4xDHxo7cV3Fa4KVZ5vp/MP10BBwjG5u1x+s4pLoGGZGWSpBnGIQED8KcBKrsywLJEPR6ohYcOSj6cvyOWrbKTEntBpxYy+WdygJsQ="

