# Required: local settings
local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# Required: deployment targets
targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

# Required: packages to be deployed
packages:
  - repo     : "snowplow-generic"
    name     : "snowplow"
    user_org : "snowplow"
    publish  : true
    override : false
    continue_on_conflict : false
    version  : <%= CMD['cat VERSION | xargs echo -n'] %>
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>
    build_commands:
      - cd root_dir/0-common/scala-core
      - sbt +test --warn && sbt +publishLocal
      - sbt project igluCoreCirce +test --warn && sbt project igluCoreCirce +publishLocal --warn
      - sbt project igluCoreJson4s +test --warn && sbt project igluCoreCirce +publishLocal --warn
      - cd root_dir/0-common/schema-ddl
      - sbt +test --warn && sbt +publishLocal
      - cd root_dir/0-common/igluctl
      - sbt test --warn
      - sbt assembly

    # Required: Artifact
    artifacts:
      - prefix : "iglu"
        suffix : ""
        type   : "zip"

        # The binaries to put in the zip
        binary_paths:
          - root_dir/0-common/igluctl/target/scala-2.12/igluctl
