# Required: local settings
local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# Required: deployment targets
targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

# Required: packages to be deployed
packages:
  - repo     : "snowplow-generic"
    name     : "iglu-server"
    user_org : "snowplow"
    publish  : true
    override : false
    continue_on_conflict : false
    version  : <%= FUNC['sbt_version(2-repositories/scala-repo-server/)'] %>
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>
    build_commands:
      - cd 2-repositories/scala-repo-server && sbt assembly && cd ../..

    # Required: Artifact
    artifacts:
      - prefix : "iglu_server_"
        suffix : ""
        type   : "zip"

        # The binaries to put in the zip
        binary_paths:
          - 2-repositories/scala-repo-server/target/scala-2.11/iglu-server-{{ packages.0.build_version }}.jar
